### ISSUE TITLE
UI Bug Checklist

### ISSUE THREAD

**Issue by Austinauth** [IBM-Bluemix/logistics-wizard#230]
This issue acts as an ongoing checklist of visual and experience based bugs that persist in the Logistics Wizard UI.

This issue should be continually updated as needed. Please feel free to add and check off bugs as they're fixed. Consult design ( @kingtraceyj @austinauth ) as needed.

### Supply Chain Dashboard:

- [x] remove vertical line in global nav
- [X] change card border to orange
- [X] Fix height of attribute tile
- [X] fix spacing between cards and map (firefox)
- [x] Change card `font-size` to `14px`
- [x] vertical center icons

**UI Bugs  - Jan 19 2017 // tjk**

### Metrics Boxes
- [ ] Retail Center needs Icon (fa-map-marker)

### Map (General)
- [ ] Align simulate storm button with zoom button ~12px from right of map
- [ ] Simulate Weather button should be title case not all caps #607188 regular
- [ ] Center Simulate weather in button
- [ ] Clear storm button needs to appear after simulate storm is clicked to get rid of storm
- [ ] Icons need updating (see hi fis for correct color and icon)
- [ ] Active Shipments needs to be brought up to map level with toggle ability 
- [ ] Add Header and toggle to map
- [ ] Implement Bluemix loader for weather loading #0F94A7

### Map (Simulate Storm is clicked)
- [ ] Implement selected state for Icon
- [ ] It looks like storm Icon is behind area affected circle
- [ ] area affected should have 15% opacity
- [ ] only storm icon should be selectable
- [ ] Weather Alert bar at top of side bar should be #E7F4F6 with text #0C7483 14px
- [ ] 20 px padding above “Snow Storm”
- [ ]  Severity should not be bold
- [ ]  “Snow Storm: & “Severity: Moderate” should be #485566
- [ ]  20 px padding Above suggested shipments 
- [ ]  Rule below Suggested shipments #DBE0E6
- [ ]  copy below suggested shipments 12px #485566
- [ ] update reject or accept new shipment box (see hi fi)
- [ ] alert: close (X) needs to function

### Distribution Center (star is clicked)
- [ ] implement selected state (see hi fis)
- [ ] only rule on left side of side bar?
- [ ] 20 px padding above “Location”
- [ ] 16 px padding btw location and manager
- [ ] 20 px padding above Outgoing shipments
- [ ] 10px padding above rule
- [ ] outgoing shipment row height should be 40px high
- [ ] status should be Title Case not All Caps

### Retail Location (location marker clicked)
- [ ] implement selected state for icon (see hi fis)
- [ ] only rule on left side of side bar?
- [ ] 20 px padding above “Location”
- [ ] 16 px padding btw location and manager
 Still discussing the need for Incoming Shipments**
- [ ] 20 px padding above Weather Forecasts
- [ ] 10px padding above rule
- [ ] Get rid of Day & Summary
- [ ] Summary replaced with Icons provided by API

### Shipment Info (truck clicked)
- [ ] implement selected state fro icon (see hi fis)
- [ ] only rule on left side of side bar?
- [ ] 20 px padding above “Staus”
- [ ] 20px padding btw each 
- [ ] Add weather Icon to current weather

### Active Shipment Tables (toggled to list)
- [ ] 40 px high heading - 14px Bold #0C7483
- [ ] heading line all the way across
- [ ] other line lines 20px padding on each side
- [ ] 40 px high rows
- [ ] Table labels left aligned
- [ ] Stats Row should be Title Case not All Caps

**Comment by cphrmky** [comment]
Perfect.  Thx Ram.

**Comment by rvennam** [comment]
Grabbed the low hanging fruit:
https://github.com/IBM-Bluemix/logistics-wizard-webui/commit/8272ead9438791d3cdcf59f71dca99dc50354917

**Comment by kingtraceyj** [comment]
@hellobrian I updated the bug list. We can sit and pair on this whenever you have time or feel free tackle some of the ones that make sense to you.
